### ISSUE TITLE
Add optional original metadata path

### ISSUE THREAD

**Issue by james-hinton** [SpatialDays/stac-generator#14]

**Comment by ivica3730k** [comment]
Required as we need to lookup assets by original metadata path when we perform a delete operation.

On delete, the blob crawler will output list of deleted metadata json files onto the Redis list.

If you really want to reduce the payload size, we can remove the metadata contents from it and just keep the file.
In that case @mountaincharlie 's validation process will need to open them.

We can discuss payload format tomorrow again.

**Comment by ivica3730k** [comment]
More info about payload format here, https://github.com/SpatialDays/os-eo-blob-cron-crawler/blob/staging/rss-rgbi25cm16bittiff-raw.md.

Just noticed that the format with "original_files" key is not consistent for update/create and delete
