### ISSUE TITLE
add BLOB_MOUNTING_CONFIGURATIONS_JSON_PATH env variable

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-generator#21]
Path to blob mounting configuration file must be an environment variable as our terraform makes it.

https://github.com/SpatialDays/gdal-info-microservice/blob/e55545f2be6c9c0f906cbf1bbe7baec39faee9a4/src/main.py#L35

![image](https://github.com/SpatialDays/stac-generator/assets/17437897/391b604a-af65-4927-a026-c5c4ce3cf4ea)

**Comment by james-hinton** [comment]
Closed by [ #90](https://github.com/SpatialDays/stac-generator/commit/90bdc5055f2ab9f2eb535a534b356c491df84548)
