### ISSUE TITLE
Use Uvicorn to run Redis Docker

### ISSUE THREAD

**Issue by james-hinton** [SpatialDays/stac-generator#35]
May need discussion.

https://github.com/SpatialDays/stac-generator/blob/staging/Dockerfile-redis#L24

**Comment by james-hinton** [comment]
How it was done before. https://github.com/SpatialDays/stac-generator/blob/staging/Dockerfile

**Comment by james-hinton** [comment]
Hmm.. Maybe uvicorn wouldn't affect anything, but if were calling it using python, we should be using poetry to call the file? @ivica3730k

**Comment by ivica3730k** [comment]
isnt uvicorn is for serving the uwsgi? will see can I add poetry. Deploying it now/

**Comment by ivica3730k** [comment]
Even better would be removing cmd from the dockerfile and specifying it in terraform how you want the container to be started

**Comment by ivica3730k** [comment]
I've messed up something with the build jobs too. Docker images are the same, so both have uvicorn cmd in them.

**Comment by james-hinton** [comment]
> Even better would be removing cmd from the dockerfile and specifying it in terraform how you want the container to be started

lets just make sure it's in the Dockerfile first

**Comment by ivica3730k** [comment]
all works now
